import Head from "next/head";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Morasilat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //  fetch the language preference here and then pass as dir property to all other props
    <html>
      <body>{children}</body>
    </html>
  );
}
