import Head from "next/head";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Morasilat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //  fetch the language preference here and then pass as dir property to all other props
    <html>
      {/* <h1 className="flex justify-center items-center text-2xl font-bold h-screen lg:hidden bg-primary-900 text-white ">
        Not available in small screens...Pls go to a large screen
      </h1> */}

      <body className="hidden lg:block">{children}</body>
    </html>
  );
}
